"""Export analysis results as Markdown or PDF."""

import base64
import io
from datetime import datetime, timezone
from typing import TYPE_CHECKING

import streamlit as st

from config import config

if config.ENABLE_PDF_EXPORT:
    try:
        from fpdf import FPDF
        from fpdf.enums import XPos, YPos

        PDF_EXPORT_AVAILABLE = True
    except ImportError:
        PDF_EXPORT_AVAILABLE = False
else:
    PDF_EXPORT_AVAILABLE = False

if TYPE_CHECKING:
    from fpdf import FPDF
    from fpdf.enums import XPos, YPos

DISCLAIMER = (
    "This analysis is for educational and demonstration purposes only. "
    "All medical imaging should be reviewed by qualified healthcare professionals "
    "for clinical decision-making."
)


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def build_markdown_report(
    image: object,
    analysis_text: str,
    model_id: str,
    additional_context: str = "",
) -> str:
    """Build a Markdown report string.

    Args:
        image: A PIL Image instance.
        analysis_text: The analysis text from the model.
        model_id: Model identifier used for the analysis.
        additional_context: Optional user-provided context.

    Returns:
        Markdown content as a string.
    """
    buf = io.BytesIO()
    image.save(buf, format="PNG")
    img_b64 = base64.b64encode(buf.getvalue()).decode("utf-8")

    lines = [
        f"# {config.APP_NAME} - Medical Image Analysis",
        "",
        f"**Date:** {_now()}",
        f"**Model:** {model_id}",
        "",
        "## Uploaded Image",
        "",
        f"![Uploaded medical image](data:image/png;base64,{img_b64})",
        "",
    ]

    if additional_context:
        lines.extend(
            [
                "## Additional Context",
                "",
                additional_context,
                "",
            ]
        )

    lines.extend(
        [
            "## Analysis",
            "",
            analysis_text,
            "",
            "---",
            "",
            f"*{DISCLAIMER}*",
            "",
            f"Generated by [{config.COMPANY}]({config.COMPANY_URL})",
        ]
    )

    return "\n".join(lines)


if PDF_EXPORT_AVAILABLE:

    class _PDF(FPDF):
        def header(self) -> None:
            self.set_font("helvetica", "B", 12)
            self.cell(
                0,
                10,
                f"{config.APP_NAME} - Medical Image Analysis",
                new_x=XPos.LMARGIN,
                new_y=YPos.NEXT,
                align="L",
            )
            self.ln(2)

        def footer(self) -> None:
            self.set_y(-15)
            self.set_font("helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, DISCLAIMER, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")


def build_pdf_report(
    image: object,
    analysis_text: str,
    model_id: str,
    additional_context: str = "",
) -> bytes:
    """Build a PDF report as bytes.

    Args:
        image: A PIL Image instance.
        analysis_text: The analysis text from the model.
        model_id: Model identifier used for the analysis.
        additional_context: Optional user-provided context.

    Returns:
        PDF file content as bytes.
    """
    if not PDF_EXPORT_AVAILABLE:
        raise RuntimeError("PDF export is unavailable because fpdf2 is not installed.")

    pdf = _PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 6, f"Date: {_now()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, f"Model: {model_id}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # Save image to a temporary in-memory buffer
    img_buf = io.BytesIO()
    image.save(img_buf, format="PNG")
    img_buf.seek(0)

    # Fit image to page width with margins
    page_width = pdf.w - 2 * pdf.l_margin
    pdf.image(img_buf, x=pdf.l_margin, w=page_width)
    pdf.ln(4)

    if additional_context:
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 6, "Additional Context", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("helvetica", "", 10)
        pdf.multi_cell(0, 5, additional_context)
        pdf.ln(2)

    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 6, "Analysis", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 5, analysis_text)

    return bytes(pdf.output())


@st.cache_data(show_spinner=False)
def cached_markdown_report(
    image_bytes: bytes,
    analysis_text: str,
    model_id: str,
    additional_context: str = "",
) -> str:
    """Cache the generated Markdown report.

    The image is serialized to bytes so Streamlit can hash it.
    """
    from PIL import Image as PILImage

    image = PILImage.open(io.BytesIO(image_bytes))
    return build_markdown_report(image, analysis_text, model_id, additional_context)


@st.cache_data(show_spinner=False)
def cached_pdf_report(
    image_bytes: bytes,
    analysis_text: str,
    model_id: str,
    additional_context: str = "",
) -> bytes:
    """Cache the generated PDF report.

    The image is serialized to bytes so Streamlit can hash it.
    """
    if not PDF_EXPORT_AVAILABLE:
        raise RuntimeError("PDF export is disabled or fpdf2 is not installed.")

    from PIL import Image as PILImage

    image = PILImage.open(io.BytesIO(image_bytes))
    return build_pdf_report(image, analysis_text, model_id, additional_context)
