"""Export analysis results as Markdown or PDF."""

import base64
import io
from datetime import datetime, timezone
from typing import TYPE_CHECKING, List, Optional

import streamlit as st
from PIL import Image as PILImage

from config import config

if TYPE_CHECKING:
    from storage.models import PhotoSnapshot

if config.ENABLE_PDF_EXPORT:
    try:
        from fpdf import FPDF
        from fpdf.enums import XPos, YPos

        PDF_EXPORT_AVAILABLE = True
    except ImportError:
        PDF_EXPORT_AVAILABLE = False
else:
    PDF_EXPORT_AVAILABLE = False

if TYPE_CHECKING:
    from fpdf import FPDF
    from fpdf.enums import XPos, YPos

DISCLAIMER = (
    "This analysis is for educational and orientation purposes only. "
    "All medical images, health photos, and photographed documents should be reviewed by "
    "qualified healthcare professionals for clinical decision-making."
)


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _image_to_data_uri(image: object) -> str:
    """Serialize a PIL image to a PNG data URI."""
    buf = io.BytesIO()
    image.save(buf, format="PNG")
    img_b64 = base64.b64encode(buf.getvalue()).decode("utf-8")
    return f"data:image/png;base64,{img_b64}"


def build_markdown_report(
    image: object,
    analysis_text: str,
    model_id: str,
    additional_context: str = "",
    additional_images: Optional[List[object]] = None,
) -> str:
    """Build a Markdown report string.

    Args:
        image: A PIL Image instance representing the primary image.
        analysis_text: The analysis text from the model.
        model_id: Model identifier used for the analysis.
        additional_context: Optional user-provided context.
        additional_images: Optional list of additional PIL images to include.

    Returns:
        Markdown content as a string.
    """
    lines = [
        f"# {config.APP_NAME} - Image Analysis Report",
        "",
        f"**Date:** {_now()}",
        f"**Model:** {model_id}",
        "",
        "## Uploaded Image(s)",
        "",
        f"![Uploaded image]({_image_to_data_uri(image)})",
        "",
    ]

    for idx, extra_image in enumerate(additional_images or []):
        lines.extend(
            [
                f"### Image {idx + 2}",
                "",
                f"![Uploaded image {idx + 2}]({_image_to_data_uri(extra_image)})",
                "",
            ]
        )

    if additional_context:
        lines.extend(
            [
                "## Additional Context",
                "",
                additional_context,
                "",
            ]
        )

    lines.extend(
        [
            "## Analysis",
            "",
            analysis_text,
            "",
            "---",
            "",
            f"*{DISCLAIMER}*",
            "",
            f"Generated by [{config.COMPANY}]({config.COMPANY_URL})",
        ]
    )

    return "\n".join(lines)


if PDF_EXPORT_AVAILABLE:

    class _PDF(FPDF):
        def header(self) -> None:
            self.set_font("helvetica", "B", 12)
            self.cell(
                0,
                10,
                f"{config.APP_NAME} - Image Analysis Report",
                new_x=XPos.LMARGIN,
                new_y=YPos.NEXT,
                align="L",
            )
            self.ln(2)

        def footer(self) -> None:
            self.set_y(-15)
            self.set_font("helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, DISCLAIMER, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")


def _add_image_to_pdf(pdf: "FPDF", image: object) -> None:
    """Add a single image to a PDF, fitting it to page width."""
    img_buf = io.BytesIO()
    image.save(img_buf, format="PNG")
    img_buf.seek(0)

    page_width = pdf.w - 2 * pdf.l_margin
    pdf.image(img_buf, x=pdf.l_margin, w=page_width)
    pdf.ln(4)


def build_pdf_report(
    image: object,
    analysis_text: str,
    model_id: str,
    additional_context: str = "",
    additional_images: Optional[List[object]] = None,
) -> bytes:
    """Build a PDF report as bytes.

    Args:
        image: A PIL Image instance representing the primary image.
        analysis_text: The analysis text from the model.
        model_id: Model identifier used for the analysis.
        additional_context: Optional user-provided context.
        additional_images: Optional list of additional PIL images to include.

    Returns:
        PDF file content as bytes.
    """
    if not PDF_EXPORT_AVAILABLE:
        raise RuntimeError("PDF export is unavailable because fpdf2 is not installed.")

    pdf = _PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 6, f"Date: {_now()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, f"Model: {model_id}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    _add_image_to_pdf(pdf, image)
    for extra_image in additional_images or []:
        _add_image_to_pdf(pdf, extra_image)

    if additional_context:
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 6, "Additional Context", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("helvetica", "", 10)
        pdf.multi_cell(0, 5, additional_context)
        pdf.ln(2)

    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 6, "Analysis", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 5, analysis_text)

    return bytes(pdf.output())


@st.cache_data(show_spinner=False)
def cached_markdown_report(
    image_bytes: bytes,
    analysis_text: str,
    model_id: str,
    additional_context: str = "",
    additional_image_bytes: Optional[List[bytes]] = None,
) -> str:
    """Cache the generated Markdown report.

    The image is serialized to bytes so Streamlit can hash it.
    """
    from PIL import Image as PILImage

    image = PILImage.open(io.BytesIO(image_bytes))
    additional_images = None
    if additional_image_bytes:
        additional_images = [PILImage.open(io.BytesIO(b)) for b in additional_image_bytes]
    return build_markdown_report(
        image, analysis_text, model_id, additional_context, additional_images
    )


@st.cache_data(show_spinner=False)
def cached_pdf_report(
    image_bytes: bytes,
    analysis_text: str,
    model_id: str,
    additional_context: str = "",
    additional_image_bytes: Optional[List[bytes]] = None,
) -> bytes:
    """Cache the generated PDF report.

    The image is serialized to bytes so Streamlit can hash it.
    """
    if not PDF_EXPORT_AVAILABLE:
        raise RuntimeError("PDF export is disabled or fpdf2 is not installed.")

    from PIL import Image as PILImage

    image = PILImage.open(io.BytesIO(image_bytes))
    additional_images = None
    if additional_image_bytes:
        additional_images = [PILImage.open(io.BytesIO(b)) for b in additional_image_bytes]
    return build_pdf_report(image, analysis_text, model_id, additional_context, additional_images)


HANDOVER_DISCLAIMER = (
    "This handover document is for orientation and preparation only. "
    "It is not a diagnosis or treatment recommendation. "
    "A qualified healthcare professional must review the original images and context."
)


def build_handover_markdown_report(
    snapshots: List["PhotoSnapshot"],
    role: str = "patient",
    user_id: str = "",
) -> str:
    """Build a Markdown handover report from a list of snapshots.

    Args:
        snapshots: Snapshots ordered from oldest to newest.
        role: Intended audience (patient, clinician, researcher).
        user_id: Optional user/session identifier.

    Returns:
        Markdown content as a string.
    """
    lines = [
        f"# {config.APP_NAME} - Handover Report",
        "",
        f"**Date:** {_now()}",
        f"**Audience:** {role.capitalize()}",
    ]
    if user_id:
        lines.append(f"**Patient/Session ID:** {user_id}")
    lines.extend(["", "## Timeline", ""])

    for idx, snapshot in enumerate(snapshots, start=1):
        lines.append(f"### Entry {idx} — {snapshot.created_at.strftime('%Y-%m-%d %H:%M UTC')}")
        if snapshot.body_site:
            lines.append(f"**Body site:** {snapshot.body_site}")
        if snapshot.encrypted_image:
            image = PILImage.open(io.BytesIO(snapshot.encrypted_image))
            lines.append(f"![Snapshot {idx}]({_image_to_data_uri(image)})")
            lines.append("")
        if snapshot.anamnesis:
            lines.extend(["**Anamnesis:**", "", snapshot.anamnesis, ""])
        if snapshot.analysis_summary:
            lines.extend(["**Summary:**", "", snapshot.analysis_summary, ""])
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            f"*{HANDOVER_DISCLAIMER}*",
            "",
            f"Generated by [{config.COMPANY}]({config.COMPANY_URL})",
        ]
    )
    return "\n".join(lines)


def build_handover_pdf_report(
    snapshots: List["PhotoSnapshot"],
    role: str = "patient",
    user_id: str = "",
) -> bytes:
    """Build a PDF handover report from a list of snapshots."""
    if not PDF_EXPORT_AVAILABLE:
        raise RuntimeError("PDF export is unavailable because fpdf2 is not installed.")

    class _HandoverPDF(FPDF):
        def header(self) -> None:
            self.set_font("helvetica", "B", 12)
            self.cell(
                0,
                10,
                f"{config.APP_NAME} - Handover Report",
                new_x=XPos.LMARGIN,
                new_y=YPos.NEXT,
                align="L",
            )
            self.ln(2)

        def footer(self) -> None:
            self.set_y(-15)
            self.set_font("helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, HANDOVER_DISCLAIMER, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")

    pdf = _HandoverPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_font("helvetica", "", 10)

    pdf.cell(0, 6, f"Date: {_now()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, f"Audience: {role.capitalize()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    if user_id:
        pdf.cell(0, 6, f"Patient/Session ID: {user_id}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 8, "Timeline", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("helvetica", "", 10)

    for idx, snapshot in enumerate(snapshots, start=1):
        pdf.set_font("helvetica", "B", 10)
        pdf.cell(
            0,
            8,
            f"Entry {idx} — {snapshot.created_at.strftime('%Y-%m-%d %H:%M UTC')}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
        )
        pdf.set_font("helvetica", "", 10)
        if snapshot.body_site:
            pdf.cell(
                0,
                6,
                f"Body site: {snapshot.body_site}",
                new_x=XPos.LMARGIN,
                new_y=YPos.NEXT,
            )
        if snapshot.encrypted_image:
            _add_image_to_pdf(pdf, PILImage.open(io.BytesIO(snapshot.encrypted_image)))
        if snapshot.anamnesis:
            pdf.set_font("helvetica", "B", 10)
            pdf.cell(0, 6, "Anamnesis:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("helvetica", "", 10)
            pdf.multi_cell(0, 5, snapshot.anamnesis)
            pdf.ln(2)
        if snapshot.analysis_summary:
            pdf.set_font("helvetica", "B", 10)
            pdf.cell(0, 6, "Summary:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("helvetica", "", 10)
            pdf.multi_cell(0, 5, snapshot.analysis_summary)
            pdf.ln(2)
        pdf.ln(4)

    return bytes(pdf.output())
